### ISSUE TITLE
solcix compile command error

### ISSUE THREAD

**Issue by WaterSo0910** [Solratic/solcix#2]
### Description

I run this command `solcix compile example.sol`
and I got error `solcix.errors.InvalidOptionError: solc does not accept 'userdoc' as an option for the '--combined-json' flag`

### Screenshots

![image](https://user-images.githubusercontent.com/55632018/234443631-84637e3b-2f6e-40d9-bd19-f123c9500a23.png)

**Comment by alan890104** [comment]
Hey @WaterSo0910, could you please provide your OS, solidity version and the solidity files for futher investigating? I have tried the below example with version 0.8.17 but there is no error :

`command line`

```bash
solcix compile  wallet.sol 
```
and `wallet.sol`

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.17;

contract EtherWallet {
    address payable public owner;

    constructor() {
        owner = payable(msg.sender);
    }

    receive() external payable {}

    function withdraw(uint _amount) external {
        require(msg.sender == owner, "caller is not owner");
        payable(msg.sender).transfer(_amount);
    }

    function getBalance() external view returns (uint) {
        return address(this).balance;
    }
}
```

**Comment by WaterSo0910** [comment]
I use poetry with python 3.10 on windows 11 and get the same error even using your example.

**Comment by alan890104** [comment]
Hey @WaterSo0910 ,
I have investigated the problem and I am pleased to inform you that we have implemented a fix. The issue was caused by the trailing `\r` in windows OS, and we have addressed it by adding `strip()` for the option.

**Comment by WaterSo0910** [comment]
BRAVO LOL🚀
